services:
  - type: web
    name: halwai-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
